Epidemiological SIR Model
========================================================

## Epidemiological Models

* Early estimation of the basic reproduction number R$_0$ as early as possible in the face of
an epidemic is crucial for public health decision making. 
* The reason for this is that knowledge of the reproduction number gives valuable information for the estimation of the transmission potential of the epidemic and for the comparison of possible epidemic management strategies. 
* In an epidemic, there is an initial stochastic phase followed by exponential growth continuing until the number of members of the population who are no longer susceptible to infection becomes a significant fraction of the population. 
* It may be possible to obtain real time data sufficient to estimate this initial exponential growth rate, and this leads to the task of using these data to estimate R$_0$.
* However, the estimate of R0 obtained depends on the specific model being used for
the epidemic. Here, I present the simplest model, the Suceptible-Infectious-Recovered (SIR) model.

## Use of application:

### Inputs values

There are 6 input values required for this model:

 * Days to be analyzed: It is required to input the number of days that the disease will be followed.
 * Transmission rate: The probability of been infected for a suceptible person.
 * Length of the infectious period: Number of days a person with the disease may infect others until he recovers from the disease.
 
 * Initial Suceptible Population: Number of people that could aquire the disease.
 * Initial Infected Population: Number of people that are infected at the begining of the study (there has to be at least one).
 * Initial Recovered Population: Number of people that are already recovered from the disease at the beginning of the study.
 
## Results

This application shows the following results:
* Graph of the suceptible and recovered population against the infected population, across the time period to be analyzed. 
* Number of suceptible - infectious - recovered people in the population at the end of the time period, 
* Basic Reproductive Number ( R$_0$ ). It is important to note that
* if this number is less than 1, then there is no epidemic threat.
* if it is 1, then the disease has reached an endemic presence
* if is greater than 1, then there is an epidemic.


